local opt = vim.opt                   -- Para consistencia

syntax = on                           -- Habilitar coloreo de sintaxís
filetype = off                        -- Suele ser 'Plugin on' pero se desactiva para que los plugins carguen correctamente

opt.autoindent = true                 -- Indenta de manera automatica
-- opt.autowrite = true                  -- Guarda el archivo automaticamente al cambiar de buffer
opt.backup  = false                   -- Cuando se guarda el archivo original se borra el backup
opt.backspace = "indent,eol,start"    -- Para que delete key funcione como se espera
opt.clipboard:append("unnamedplus")   -- Habilitar clipboard
-- opt.cmdheight = 2                     -- Altura de la barra de comandos
-- otp.conceallevel = 3                  -- Ocultar caracteres especiales
opt.compatible = false                -- No intentar ser vi compatible (no se exactamente porque) (no necesario en Nvim)
opt.cursorline = true                 -- Mostrar una linea donde esta posicionado el cursor
opt.encoding = "utf-8"                -- Codificación de archivos
-- opt.equalalways = false               -- No ajustar tamaño de ventanas al abrir/cerrar otras
-- opt.errorbells = false                -- No hacer sonido al error
opt.expandtab = true                  -- Convierte tabs en espacios
opt.exrc = true                       -- Habilita la lectura de código .vimrc .exrc y .gvimrc en el directorio actural
opt.formatoptions = "tcqrn1"          -- Un poco de todo esto https://vimhelp.org/change.txt.html#fo-table
opt.hlsearch = true                   -- Resaltar coincidencias
opt.hidden = true                     -- Buffers abiertos en segundo plano
opt.ignorecase = true                 -- Búsqueda insensitiva
opt.incsearch  = true                 -- Búsqueda incremental
-- opt.list = true                       -- NN
-- opt.listchars = "tab:▸ ,trail:·,extends:❯,precedes:❮" -- NN
-- otp.laststatus = 3                    -- NN
opt.modeline = false                  -- Evita ejecución de código (malicioso) automatico
opt.modelines = 0                     -- Evita ejecución de código (malicioso) automatico
opt.mouse = a                         -- Habilitar uso de mouse
opt.number = true                     -- Ver números de línea
opt.numberwidth = 1                   -- Ancho de los números de línea
-- opt.path+ = **                        -- Búsqueda en subfolder y 'tab-completion' en todas las tareas relacionadas
opt.relativenumber = true             -- Mostrar n√∫mero de linea relativo
-- opt.replace = true                    -- Reemplazar texto seleccionado
opt.ruler = true                      -- Mostrar posición del cursor en barra inferior (VIM)
opt.scrolloff = 8                     -- Cantidad de líneas mínimas sobre y debajo del cursor para realizar el scroll
opt.secure = true                     -- Evita ejecución de codigo .vimrc y .exrc en directorio actual.
opt.shiftwidth = 2                    -- No se que es
opt.shortmess = "filnxtToOFc"          -- Ocultar mensajes de inicio
opt.showcmd = true                    -- Mostrar comandos ejecutados
opt.showmatch = true                  -- Resaltar pareja de signos de apertura/cierre de código
opt.showmode = false                  -- Ocultar modo activado
-- opt.showtabline = 2                   -- Mostrar pestañas
-- opt.sidescroll = 1                    -- Cantidad de columnas a desplazar al hacer scroll horizontal
opt.signcolumn = "yes"                -- Muestra ~ en la izq de cada fila. Necesario especificar el ancho con algunos plugins
opt.smartcase  = true                 -- Búsqueda si al menos contiene una letra mayúscula
opt.smartindent = true                -- Indenta automáticamente
opt.softtabstop = 2                   -- No se que es
opt.splitbelow = true                 -- split horizontal a la ventana inferior
-- opt.splitkeep = "screen              -- Mantener tamaño de ventanas al abrir/cerrar otras
opt.splitright = true                 -- split vertical a la ventana derecha
opt.sw = 2                            -- Indentar con espacio
opt.swapfile = false                  -- Desabilita el archivo temporal
opt.tabstop = 2                       -- Indentar con tabulación
opt.termguicolors = true              -- Necesario para que funcione el theme correctamente
opt.textwidth = 79                    -- Define el ancho de texto máximo
opt.ttyfast = true                    -- Acelera el scroll (o eso dicen)
opt.undodir = "/tmp/.nvim/undodir"    -- Directorio 'cache' de modificaciones de archivo. Dejar permisos 700 por seguridad
opt.undofile = true                   -- Habilita la restauración de modificaciones de archivo
-- opt.updatetime = 50                   -- Tiempo de actualización del guardado del buffer
opt.visualbell = true                 -- Parpadeo de cursor en vez de sonido
opt.wildmenu = true                   -- Muestra todas las coincidencias cuando se presiona tab
opt.wrap = true                      -- Ajuste de texto al ancho máximo
